### ISSUE TITLE
pysigma re attribute exception 

### ISSUE THREAD

**Issue by THAVASIGTI** [CybercentreCanada/pysigma#13]
``` python
Python 3.6.9 (default, Dec  8 2021, 21:08:43) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysigma
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gti/pysys/pysigma/pysigma/__init__.py", line 2, in <module>
    from .pysigma import PySigma
  File "/home/gti/pysys/pysigma/pysigma/pysigma.py", line 12, in <module>
    from . import signatures
  File "/home/gti/pysys/pysigma/pysigma/signatures.py", line 38, in <module>
    Query = Optional[Union[str, re.Pattern]]
AttributeError: module 're' has no attribute 'Pattern
```

**Comment by cccs-rs** [comment]
Seems to be an issue specifically with Python3.6 and the built-in `re` module. We can switch this to use the `regex` library.

**Comment by cccs-rs** [comment]
If there are further issues with the library, do let us know! 😀
